# Generated by Django 4.0.3 on 2022-03-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('occupation', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=80)),
                ('postalcode', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Postal code')),
            ],
        ),
    ]
