# Generated by Django 4.0.3 on 2022-03-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_visitors', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Max amount of visitors')),
                ('address', models.CharField(max_length=80)),
                ('postalcode', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Postal code')),
            ],
        ),
    ]
