# Generated by Django 4.0.2 on 2022-04-29 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='age',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='postalcode',
            field=models.IntegerField(null=True),
        ),
    ]
