# Generated by Django 4.0.3 on 2022-04-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='is_zoo_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
