# Generated by Django 4.0.3 on 2022-05-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zooproject', '0002_alter_worker_age_alter_worker_postalcode'),
        ('zooproject', '0002_webuser_is_zoo_staff_alter_webuser_is_staff'),
    ]

    operations = [
    ]
