# Generated by Django 4.0.4 on 2022-05-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zooproject', '0003_alter_animal_staff_id_alter_animal_zoo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='veterinary_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zooproject.veterinary'),
        ),
    ]
