# Generated by Django 4.0.2 on 2022-04-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooproject', '0003_alter_veterinary_number_assigned_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
